### ISSUE TITLE
Typo in Wiki DeZeroをiPhoneで動かす

### ISSUE THREAD

**Issue by ftnext** [oreilly-japan/deep-learning-from-scratch-3#10]
iPhoone というtypoがありました

> iPhoneのアプリに、Pythonistaがあります。このPythonistaというアプリを使うと、iPhoone上でPythonを動かすことができます。

修正後（`変更箇所`）
→ iPhoneのアプリに、Pythonistaがあります。このPythonistaというアプリを使うと、`iPhone`上でPythonを動かすことができます。

wikiへのプルリクエストの送り方がよくわからなかったので、Issueでお知らせします

**Comment by koki0702** [comment]
ありがとうございます。
