### ISSUE TITLE
isinstanceの括弧が閉じていない

### ISSUE THREAD

**Issue by kirinsannnnnnnnnn** [oreilly-japan/deep-learning-from-scratch-3#14]
https://github.com/oreilly-japan/deep-learning-from-scratch-3/commit/ee24aa6d9d1eccce145769cd6e6f38f62d270850
こちらのリファクタリングにてisinstanceのカッコを閉じ忘れて`axes=(None,)`の場合の条件分岐が変わってしまったように見えました。
https://github.com/oreilly-japan/deep-learning-from-scratch-3/blob/976e9bf3ad556ce06e1d6c2da78db02d52b4b6a1/dezero/core.py#L147

**Comment by koki0702** [comment]
ご指摘どおり、カッコを閉じ忘れていました。
修正させていただきます。
ありがとうございます。
