### ISSUE TITLE
 Momentum SGDについて(step46)

### ISSUE THREAD

**Issue by kawase621** [oreilly-japan/deep-learning-from-scratch-3#21]
p.359の Momentum SGDクラスのupdate_one関数についてです。
vという変数にself.vsというインスタンス変数の特定の要素(self.vs[v_key])が代入され、その後変数vのほうが更新されていますが、この方法の場合、インスタンス変数である辞書(self.vs)の持つ値は変わらない、つまり最初に呼ばれた時に設定した0のままになってしまうのではないでしょうか？
その結果、forループでupdate_one関数が呼ばれる度に変数vが0に更新されてしまい、学習が上手く進まないように思います。
理解が不十分で的外れな指摘となっていたら申し訳ありません。

**Comment by koki0702** [comment]
ご質問ありがとうございます。

まずは答えの方ですが、これは `self.vs` の持つ値は毎回更新されます。
理由を順に説明していくと次のようになります。

```
# self.vs[v_key] = np.zeros_like(...)
v = self.vs[v_key]
```

今、`v` は `ndarray` インスタンスである `self.vs[v_key]` を参照しています。

```
v *= self.momentum
```

そして上のように `*=` とありますが、ここがポイントです。
`ndarray` インスタンスの場合、これは**インプレース演算** が行われます。

インプレース演算とは、値を新たに生成するのではなく、既存のデータを上書きすることです。
そのため、`v` が参照している`ndarray` インスタンスは上書きされることになります。

```
v -= self.lr * param.grad.data
```

その次に、上のコードが実行されますが、ここでも `-=` とインプレース演算が使われます。


以上より、`self.vs` の値は呼び出されるたびに更新されていきます。

**Comment by koki0702** [comment]
ちなみに、本書のp.502で「インプレース演算」の説明をしていました。
（ご参考までに）

<img width="956" alt="Screen Shot 2020-07-09 at 16 44 58" src="https://user-images.githubusercontent.com/515809/87012000-9e9cfb80-c203-11ea-8a5c-033e68bfba24.png">

**Comment by kawase621** [comment]
なるほど！
リストやndarrayインスタンスなど変更可能なオブジェクトを参照している場合はインプレース演算が行われるのですね。
丁寧な解説ありがとうございます。
大変助かりました。
