### ISSUE TITLE
p381のsteps/step49.py のコードの記述ミス

### ISSUE THREAD

**Issue by tetsuomiyoshi** [oreilly-japan/deep-learning-from-scratch-3#27]
p381のsteps/step49.py のコードですが、７行目の

model = MLP((hidden_size, 10))
は、
model = MLP((hidden_size, 3))
の間違いではないでしょうか？

**Comment by koki0702** [comment]
ご指摘どおり誤りです。
下記の通り修正しました。

ありがとうございます。

https://github.com/oreilly-japan/deep-learning-from-scratch-3/commit/94a2a916732a86aee050c98506ec2aa5a464794d
https://github.com/oreilly-japan/deep-learning-from-scratch-3/wiki/Errata
