### ISSUE TITLE
Variableクラスのmatmulメソッドの設定でmatmaulとtypoしている

### ISSUE THREAD

**Issue by ftnext** [oreilly-japan/deep-learning-from-scratch-3#29]
## 現状

dezero/core.py の 345行目
https://github.com/oreilly-japan/deep-learning-from-scratch-3/blob/a19876ccc265137d68d6559c6bc2b7c956b733a6/dezero/core.py#L345

```python
def setup_variable():
    # 省略

    Variable.matmaul = dezero.functions.matmul
    # 省略
```

## 影響

ステップ41の例をVariableインスタンスのメソッドで実行しようとすると、
typoが原因で、matmulメソッドの呼び出しでエラーが発生します。
※masterブランチをcloneし、setup.pyを実行して環境構築しています

```python
>>> import numpy as np
>>> from dezero import Variable
>>> x = Variable(np.random.randn(2, 3))
>>> W = Variable(np.random.randn(3, 4))
>>> # y = dezero.functions.matmul(x, W) 相当のコード
>>> y = x.matmul(W)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Variable' object has no attribute 'matmul'
>>> y = x.matmaul(W)
>>> y.shape
(2, 4)
```

## 修正

```python
def setup_variable():
    # 省略

    Variable.matmul = dezero.functions.matmul
    # 省略
```

**Comment by koki0702** [comment]
ありがとうございます。修正しました。
https://github.com/oreilly-japan/deep-learning-from-scratch-3/commit/06419d7fb2e7ea19aa3719efc27795edbdc41a1f
