### ISSUE TITLE
オライリー・ジャパンへの連絡先のメールアドレスの@が全角のため、連絡する際に混乱しました

### ISSUE THREAD

**Issue by ftnext** [oreilly-japan/deep-learning-from-scratch-3#30]
### README

> 正誤表ページに掲載されていない誤植や間違いなどを見つけた方は、✉️ japan＠oreilly.co.jpまでお知らせください。

### Errata

> 本ページに掲載されていない誤植など間違いを見つけた方は、japan＠oreilly.co.jpまでお知らせください。

## 問題

上記のメールアドレスは2つとも@が**全角**になっています。
メールアドレスをコピペしてEメールを送ろうとしたところ、
「メールアドレスが認識できない」とエラーが表示され、送れませんでした

>The address "japan＠oreilly.co.jp" in the "To" field was not recognized. (Gmailのエラーメッセージ)

## Workaround

オライリー・ジャパンが公開しているメールアドレスと比較したところ、@に全角・半角の違いがあることがわかりました
https://www.oreilly.co.jp/company/

オライリー・ジャパンが公開しているメールアドレス（@が半角のもの）を使用したところ、Eメールを送信できました

## 要望

@を半角にしていただけますと、誤植を報告する人が私のように混乱することはなくなると考えます。

意図を持って@を全角にしているのでしたら
「※@は半角に変換してからメールを送信してください」
のような注釈を記載すると、誤植を報告する人にとって親切と考えます

**Comment by koki0702** [comment]
ありがとうございます。
@を半角に修正しました。
