### ISSUE TITLE
Better to include Chainer as external dependencies

### ISSUE THREAD

**Issue by yoheikikuta** [oreilly-japan/deep-learning-from-scratch-3#6]
### Version

```python
import dezero
dezero.__version__
# '0.0.11'
```

Some tests depend on Chainer (for example, https://github.com/oreilly-japan/deep-learning-from-scratch-3/blob/master/tests/test_conv2d.py#L6).
After Chainer is installed via pip, all tests run successfully.

I guess it's better to add Chainer is one of the external dependencies to README.

**Comment by wakamezake** [comment]
I think so. And this code depend on Chainer(https://github.com/oreilly-japan/deep-learning-from-scratch-3/blob/81cbe3fc3e45560e0d30289887fe8f6f6533ae07/steps/step59.py#L4-L6)

**Comment by ftnext** [comment]
I think so too.

proposal (`setup.py`)

```python:
setup(name='dezero',
      ...
      extras_require={
            'develop': ['chainer']
      },
      ...
      )
```

And `pip install -e .[develop]`

ref: https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

**Comment by koki0702** [comment]
Thanks for suggestions!

Now Chainer is only needed at the unittests.
So Chainer is not included at `setup.py`, but added at travis CI setup.
https://github.com/oreilly-japan/deep-learning-from-scratch-3/blob/master/.travis.yml#L7

(`[develop]` option is a good idea !)
